### ISSUE TITLE
Please transfer repository to tc39

### ISSUE THREAD

**Issue by erights** [tc39/proposal-export-default-from#1]
See https://github.com/tc39/proposals/issues/44

**Comment by jdalton** [comment]
@leebyron If you could transfer the repo to the tc39 org @benjamn (of Meteor) and myself (of JS Foundation) would like to champion this and [your other proposal](https://github.com/leebyron/ecmascript-export-ns-from/issues/4).

**Comment by leebyron** [comment]
Awesome! Glad to hear you guys are picking these up. I'll move them

**Comment by benjamn** [comment]
Thanks @leebyron! We've been using this syntax for a while now and love it.

**Comment by jdalton** [comment]
@leebyron I'm not sure if it's possible to transfer directly to a GitHub org. If you run into issues you can transfer to @bterlson as a go between.

**Comment by bterlson** [comment]
@jdalton @leebyron transfer to me (please ping on twitter/irc/email to make sure I'm around, it has a time limit) and I will move to tc39 org. I haven't tried a direct org transfer in a while, so maybe it works?

**Comment by jdalton** [comment]
Ping @leebyron.

**Comment by leebyron** [comment]
Yeah I can't transfer directly to tc39. I'll try bterlson

**Comment by leebyron** [comment]
Thanks for your patience, all. I'm super excited you're going to champion these.

I've transferred them to you, @bterlson - I assume you can get them into @tc39 from there.

**Comment by bterlson** [comment]
Done!

**Comment by jdalton** [comment]
Sweet, could @benjamn  and I be added as collaborators.

**Comment by bterlson** [comment]
@jdalton done (also on the other repo).
